sonar.projectKey=EstudoHub_Pro_4.0
sonar.projectName=EstudoHub Pro 4.0
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/venv/**,**/storage/**,**/storage_k/**,vault/**,backend/tests/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/test-reports/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
